### ISSUE TITLE
FR28. Restaurant Directory

### ISSUE THREAD

**Issue by fahmi009** [WSU-4110/LeftOvr#28]
|FR28. Restaurant Directory|
|---|
|**Goal**: The goal is to ensure information about the restaurant is stored
**Stakeholders:** Customer and restaurant|
| **Description:** The information provided by the restaurant should be kept securely under accurate restaurant user ID. The information includes logo image, cover picture, meal picture, available meals, restaurant contact information, operation hours. This way the customer will be available to view correct and accurate information about the restaurant|
| **Origin:** Based on the initial project specification document, team members came up with this description during the seventh meeting.|
| **Version:** 1.0  |
|**Date:** 09/11/2019|  **Priority:** 1 |

**Comment by White12487** [comment]
In order to start this, we need to update the restaurant sign up page to allow for them to input their business pic/avatar pic then we can display it in the header in every page if applicable. I can create the opening in the database for media uploads but unless the html pages are updated the user won't be able to use this feature.

**Comment by fahmi009** [comment]
Gotchu i will change up the registration part and create a next tab for both customers and restaurants registration pages. For customers, it will upload a profile pic and for restaurant it will be header image and logo image. ❤️
